### ISSUE TITLE
Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by pbeneteau** [rsz44/python-coinmarketcap#3] opened 2021-12-08 01:53 UTC
I get this error 50% of the times when using `cryptocurrency_info()`:

`Expecting value: line 1 column 1 (char 0)`

**Comment by grapp-project** [comment] 2021-12-13 17:11
Hello,

Surprising error. It seems to be a JSON parser error but I can't assure it like that, I can't reproduce it. Can you give me an example code, the console return please and the Python version used please?

I'll try to answer it and provide a fix if needed as soon as possible.

**Comment by rsz44** [comment] 2021-12-13 17:11
Hello,

Surprising error. It seems to be a JSON parser error but I can't assure it like that, I can't reproduce it. Can you give me an example code, the console return please and the Python version used please?

I'll try to answer it and provide a fix if needed as soon as possible.

**Comment by pbeneteau** [comment] 2021-12-13 17:17
I think it is when I send several requests in a loop with a large amount of ids. For example 1000 ids (which is the max limit) for the cryptocurrency info endpoint. Some of the queries of the same loop will throw this error.

**Comment by rsz44** [comment] 2021-12-13 17:46
Unfortunately I won't be able to help you more than that if I can't reproduce the problem. If you can provide me, as requested above, the relevant code that will allow me to reproduce the error (without your API key, of course), the console return and the version of Python used, I might be able to help you.

If I am to understand that this is coming from your code and not from the library, then I will close the issue, even if your problem does not seem to be solved. Can you confirm this for me?

**Closed as not planned** 2022-11-04 08:58 UTC
